version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiwah-ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-http://localhost:8000}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
    restart: unless-stopped 